// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb_OMDIGG0BD9NRWv6EyGECfh_g--maF4',
    appId: '1:1028720840314:web:9cf28e2f70ba3280c335c3',
    messagingSenderId: '1028720840314',
    projectId: 'studentplanner-3ef3a',
    authDomain: 'studentplanner-3ef3a.firebaseapp.com',
    storageBucket: 'studentplanner-3ef3a.firebasestorage.app',
    measurementId: 'G-E8Y0CND6WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgKxoOYjp9A0wIim8U3J1jDUJ0KJweIhw',
    appId: '1:1028720840314:android:a2bda2e5347143c9c335c3',
    messagingSenderId: '1028720840314',
    projectId: 'studentplanner-3ef3a',
    storageBucket: 'studentplanner-3ef3a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq_kS4pDgWDNTwvQALJxjXrHfK3nggLa8',
    appId: '1:1028720840314:ios:236e24c15ecf6d89c335c3',
    messagingSenderId: '1028720840314',
    projectId: 'studentplanner-3ef3a',
    storageBucket: 'studentplanner-3ef3a.firebasestorage.app',
    iosBundleId: 'com.example.studentPlanner',
  );
}
