// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-fegc2X2_68ymHnlhSTpqSvf8vCMZMs',
    appId: '1:212536936154:web:c07c53d77955f7c64b07e3',
    messagingSenderId: '212536936154',
    projectId: 'student-planner-app-2026-942bd',
    authDomain: 'student-planner-app-2026-942bd.firebaseapp.com',
    storageBucket: 'student-planner-app-2026-942bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU9Ko3U72bh0_JEkLTcERabbLOBB7O4VI',
    appId: '1:212536936154:android:aab627202b7fde904b07e3',
    messagingSenderId: '212536936154',
    projectId: 'student-planner-app-2026-942bd',
    storageBucket: 'student-planner-app-2026-942bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0gsSz_r3Zmym4cjHT2aQneqBIvQbrqsI',
    appId: '1:212536936154:ios:b06cd90955ddb1ea4b07e3',
    messagingSenderId: '212536936154',
    projectId: 'student-planner-app-2026-942bd',
    storageBucket: 'student-planner-app-2026-942bd.firebasestorage.app',
    iosBundleId: 'com.example.studentPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0gsSz_r3Zmym4cjHT2aQneqBIvQbrqsI',
    appId: '1:212536936154:ios:b06cd90955ddb1ea4b07e3',
    messagingSenderId: '212536936154',
    projectId: 'student-planner-app-2026-942bd',
    storageBucket: 'student-planner-app-2026-942bd.firebasestorage.app',
    iosBundleId: 'com.example.studentPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG-fegc2X2_68ymHnlhSTpqSvf8vCMZMs',
    appId: '1:212536936154:web:6ba3e79d084db7564b07e3',
    messagingSenderId: '212536936154',
    projectId: 'student-planner-app-2026-942bd',
    authDomain: 'student-planner-app-2026-942bd.firebaseapp.com',
    storageBucket: 'student-planner-app-2026-942bd.firebasestorage.app',
  );
}
